services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=taskfy'
      - 'MYSQL_PASSWORD=taskfy'
      - 'MYSQL_ROOT_PASSWORD=taskfy'
      - 'MYSQL_USER=taskfy'
    ports:
      - '3360:3306'
